name: deploy stock back
on: [push]
env:
  IMAGE: stock-back
  VERSION: 3.3.1
jobs:

  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Création du dossier sur le serveur.."
            mkdir -p /opt/applications/stock/${{env.IMAGE}}
            echo "Liste des fichiers :"
            ls -al /opt/applications/stock/

  generate-image:
    name: generer une image
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps:
      - name: cloner le repertoire
        uses: actions/checkout@master
      - name: setup java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generer and push image
        run: |
          ./mvnw clean package spring-boot:build-image \
#          -Dspring-boot.build-image.imageName=docker.io/sogoredev/gestion-de-produit:0.0.1-SNAPSHOT \
          -Ddocker.publishRegistry.username=${{secrets.DCK_USERNAME}} \
          -Ddocker.publishRegistry.password=${{secrets.DCK_PASSWORD}} \
          -Dspring-boot.build-image.publish=true \
          -Dmaven.test.skip=true

  run-container:
    name: generer un container
    runs-on: ubuntu-latest
    needs: [ 'create-folder','generate-image' ]
    steps:
      - name: cloner le repertoire
        uses: actions/checkout@master
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "compose.yml"
          target: /opt/applications/stock/${{env.IMAGE}}
      - name: execute commands to run container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo DB_HOST="${{ secrets.DB_HOST }}" >> /opt/applications/stock/${{env.IMAGE}}/.env
            echo DB_USERNAME="${{ secrets.DB_USERNAME }}" >> /opt/applications/stock/${{env.IMAGE}}/.env
            echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> /opt/applications/stock/${{env.IMAGE}}/.env
            docker compose -f /opt/applications/stock/${{env.IMAGE}}/compose.yml up -d