name: deploy stock back
on: [push]
jobs:

  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Création du dossier sur le serveur..."
            mkdir -p /opt/applications/stock/Gestion-de-stock
            echo "Liste des fichiers :"
            ls -al /opt/applications/stock/