name: deploy stock back
on: [push]
jobs:

  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Création du dossier sur le serveur.."
            mkdir -p /opt/applications/stock/stock-back
            echo "Liste des fichiers :"
            ls -al /opt/applications/stock/

  generate-image:
    name: generate image
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps:
      - name: cloner le repertoire
        uses: actions/checkout@master
      - name: setup java version
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' #test
          java-version: '17'
      - name: Generate and push image
        run: |
          ./mvnw clean package spring-boot:build-image \
          -Ddocker.publishRegistry.username=${{ secrets.DCK_USERNAME }} \
          -Ddocker.publishRegistry.password=${{ secrets.DCK_PASSWORD }} \
          -Dspring-boot.build-image.publish=true \
          -Dmaven.test.skip=true